services:
  frontend:
    build:
      context: .       # envia TODO o monorepo ao daemon
      dockerfile: Dockerfile   # o Dockerfile de 4 estágios
      target: runner            # vamos gerar a imagem final “runner”
      args:
        VITE_API_URL: ${BACKEND_URL:-http://api:8000}
    environment:
      - VITE_API_URL=${BACKEND_URL:-http://api:8000}
    ports:
      - "3000:80"
    restart: unless-stopped
