services:
  frontend:
    build: .
    image: climatrak-frontend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: "http://backend:8000/api"
    networks:
      - appnet

networks:
  appnet:
    external: true
