version: '3.9'
services:
  backend:
    image: ghcr.io/climatrak/traknor-backend:latest
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
    environment:
      - VITE_API_URL=/api
    ports:
      - "3000:80"
    depends_on:
      - backend
