services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Passa a variável para o ARG VITE_API_URL no Dockerfile
        VITE_API_URL: ${BACKEND_URL:-/api} 
    ports:
      - "3000:80"
    environment:
      # Garante que a variável também esteja disponível se necessário
      - VITE_API_URL=${BACKEND_URL:-/api}