# docker-compose.yml (VERSÃO INCORRETA)

services:
  frontend:
    build:
      context: . # <--- Este é o problema
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    # ... resto da configuração
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL} # 3. (Importante) Garante que a variável seja lida pelo Vite