name: CI

on:
  push:
    branches:
      - develop
      - "feat/**"
      - "fix/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Restore pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Frontend Quality Gate
        run: |
          pnpm install
          pnpm lint
          pnpm --filter frontend exec tsc --noEmit
          pnpm --filter frontend build
