name: docker-smoke

on:
  pull_request:
    paths:
      - Dockerfile
      - docker-compose.yml
      - '.docker/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build compose services
        run: docker compose build
