name: Frontend CI

on:
  push:
    branches:
      - develop
      - 'feat/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm --filter frontend build
      - name: Build Storybook
        run: pnpm --filter frontend build-storybook
        if: false
