name: Frontend CI

on:
  push:
    branches:
      - develop
      - "feat/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Restore pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --registry ${{ env.NPM_REGISTRY }}
        env:
          NPM_REGISTRY: https://registry.npmmirror.com
      - name: Build frontend
        run: pnpm --filter frontend build
