name: Frontend CI

on:
  push:
    branches:
      - develop
      - "feat/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Restore pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --registry ${{ env.NPM_REGISTRY }}
        env:
          NPM_REGISTRY: https://registry.npmmirror.com
      - name: Check OpenAPI types up-to-date
        run: pnpm api:check
      - name: Lint
        run: pnpm lint
      - name: Run unit tests with coverage
        run: pnpm test:coverage
      - name: Build
        run: pnpm --filter frontend build
      - name: Build Storybook
        run: pnpm --filter frontend build-storybook
        if: false
